// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Acklann.Traneleon
{
    static class Vsix
    {
        public const string Id = "WebFlow.VSIX.c52cbe28-691f-4105-9fd8-41e5bac86278";
        public const string Name = "WebFlow";
        public const string Description = @"Automatically transpile, minify and/or bundle your web assets when your file is saved or before your project is built.";
        public const string Language = "en-US";
        public const string Version = "0.0.31";
        public const string Author = "Ackara";
        public const string Tags = "web compile minify typescript sass images";
    }
}
